/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class j3d_Scene */

#ifndef _Included_j3d_Scene
#define _Included_j3d_Scene
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     j3d_Scene
 * Method:    init
 * Signature: (Lj3d/Graphics;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_j3d_Scene_init
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     j3d_Scene
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_j3d_Scene_close
  (JNIEnv *, jobject);

/*
 * Class:     j3d_Scene
 * Method:    getRootNodeHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_j3d_Scene_getRootNodeHandle
  (JNIEnv *, jobject);

/*
 * Class:     j3d_Scene
 * Method:    getNodeHandle
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_j3d_Scene_getNodeHandle__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     j3d_Scene
 * Method:    getNodeHandle
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_j3d_Scene_getNodeHandle__I
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
