/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class j3d_SceneNode */

#ifndef _Included_j3d_SceneNode
#define _Included_j3d_SceneNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     j3d_SceneNode
 * Method:    rotateX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_j3d_SceneNode_rotateX
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     j3d_SceneNode
 * Method:    rotateY
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_j3d_SceneNode_rotateY
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     j3d_SceneNode
 * Method:    rotateZ
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_j3d_SceneNode_rotateZ
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     j3d_SceneNode
 * Method:    translate
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_j3d_SceneNode_translate
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     j3d_SceneNode
 * Method:    scale
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_j3d_SceneNode_scale
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
