/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class j3d_Window */

#ifndef _Included_j3d_Window
#define _Included_j3d_Window
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     j3d_Window
 * Method:    init
 * Signature: (IILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_j3d_Window_init
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     j3d_Window
 * Method:    getMouseHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_j3d_Window_getMouseHandle
  (JNIEnv *, jobject);

/*
 * Class:     j3d_Window
 * Method:    getKeyboardHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_j3d_Window_getKeyboardHandle
  (JNIEnv *, jobject);

/*
 * Class:     j3d_Window
 * Method:    getGraphicsHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_j3d_Window_getGraphicsHandle
  (JNIEnv *, jobject);

/*
 * Class:     j3d_Window
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_j3d_Window_close
  (JNIEnv *, jobject);

/*
 * Class:     j3d_Window
 * Method:    poll
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_j3d_Window_poll
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
