/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class j3d_Scene */

#ifndef _Included_j3d_Scene
#define _Included_j3d_Scene
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     j3d_Scene
 * Method:    load
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_j3d_Scene_load
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
