/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class j3d_Mouse */

#ifndef _Included_j3d_Mouse
#define _Included_j3d_Mouse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     j3d_Mouse
 * Method:    nextEvent
 * Signature: ()Lj3d/MouseEvent;
 */
JNIEXPORT jobject JNICALL Java_j3d_Mouse_nextEvent
  (JNIEnv *, jobject);

/*
 * Class:     j3d_Mouse
 * Method:    flushEvents
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_j3d_Mouse_flushEvents
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
