/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class j3d_Graphics */

#ifndef _Included_j3d_Graphics
#define _Included_j3d_Graphics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     j3d_Graphics
 * Method:    render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_j3d_Graphics_render
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
